name: ci

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Get requirements
        run: |
          mkdir -p .venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - run: |
          source .venv/bin/activate
          make home
      - run: |
          source .venv/bin/activate
          make pdf
      - run: |
          source .venv/bin/activate
          make zip
      - run: |
          source .venv/bin/activate
          make test
      - run: |
          source .venv/bin/activate
          mkdocs gh-deploy --force
